### ISSUE TITLE
cross-origin stuff

### ISSUE THREAD

**Issue by hupo376787** [bitmovin/bitmovin-player-windows-app-demo#4]
Hi, guys. We are using uwp webview, inside our app, we use bitmovin to play hls. But our hls content has origin restrict. So we added ms-appx-web to our server.
From the image, we can see that our hls has the "ms-appx-web", but bitmovin still can't play it.

![image](https://user-images.githubusercontent.com/14960168/117777748-7d67ca00-b26f-11eb-8d94-9b3a9079ac2f.png)

**Comment by dweinber** [comment]
Hi @hupo376787, if you have any questions or issues with this SDK or its examples, or you require other technical support for our services, please log in to your Bitmovin Dashboard at https://bitmovin.com/dashboard and [create a new support case](https://bitmovin.com/dashboard/support/cases/create). Our team will get back to you as soon as possible :+1:
