### ISSUE TITLE
Atleast it should show the controls  like seekbar, volume etc

### ISSUE THREAD

**Issue by qamersayeed** [bitmovin/bitmovin-player-windows-app-demo#5]

**Comment by dweinber** [comment]
If you have any questions or issues with this SDK or its examples, or you require other technical support for our services, please log in to your Bitmovin Dashboard at https://bitmovin.com/dashboard and [create a new support case](https://bitmovin.com/dashboard/support/cases/create). Our team will get back to you as soon as possible :+1:
